// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_staging.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsStaging {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web; // ← return Web config instead of throwing error
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR-STAGING-WEB-APIKEY',
    authDomain: 'habitai-staging.firebaseapp.com',
    projectId: 'habitai-staging',
    storageBucket: 'habitai-staging.appspot.com',
    messagingSenderId: '629170845083',
    appId: '1:629170845083:web:XXXXXXXXXXXX', // From Firebase Web app
    measurementId: 'G-XXXXXXX', // Optional
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA0fGkC_dWEQ61TtHycBfb93zGpOzGd0A',
    appId: '1:629170845083:android:82874e1c9e80ada9701d3e',
    messagingSenderId: '629170845083',
    projectId: 'habitai-staging',
    storageBucket: 'habitai-staging.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBuHFwK8IaME5LCOCf3R6Exwg6euxKjWA',
    appId: '1:629170845083:ios:1643bfc916c77097701d3e',
    messagingSenderId: '629170845083',
    projectId: 'habitai-staging',
    storageBucket: 'habitai-staging.firebasestorage.app',
    iosClientId: '629170845083-2tpq9cgvu1t20d66ptflq1rcgh5uqj6v.apps.googleusercontent.com',
    iosBundleId: 'com.jofu.habitai.staging',
  );
}
