// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz4zPGEAP-1waO2lD6Zc6SPE4ff9jQDCg',
    appId: '1:789343134479:android:e7a415fc4f52d4031c947a',
    messagingSenderId: '789343134479',
    projectId: 'question-app-7b8e6',
    storageBucket: 'question-app-7b8e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeLPrxn5A8TRnWVN5ve9WkL9POVtUn5Oc',
    appId: '1:642857860578:ios:800edf9c9f47677e770dbb',
    messagingSenderId: '642857860578',
    projectId: 'sukya-89421',
    storageBucket: 'sukya-89421.firebasestorage.app',
    iosBundleId: 'com.app.waterBottle',
  );
}
