// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsProd {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmH8z31ptDm3WVXU7npE2f8SOaejIbChc',
    appId: '1:1090097185211:web:cca50d0c11d583ef91849e',
    messagingSenderId: '1090097185211',
    projectId: 'habitai---habit-tracker-12d13',
    authDomain: 'habitai---habit-tracker-12d13.firebaseapp.com',
    storageBucket: 'habitai---habit-tracker-12d13.firebasestorage.app',
    measurementId: 'G-XQPXHEZM0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0QtTZ05OB5eoRI4dTO70QMHZ1I3Qhyjs',
    appId: '1:1090097185211:android:d23122f0636cb20291849e',
    messagingSenderId: '1090097185211',
    projectId: 'habitai---habit-tracker-12d13',
    storageBucket: 'habitai---habit-tracker-12d13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHNl_Ys4big9EEfTouLpbXSa9h_5D4vgs',
    appId: '1:1090097185211:ios:3d2de85e5baa5c4c91849e',
    messagingSenderId: '1090097185211',
    projectId: 'habitai---habit-tracker-12d13',
    storageBucket: 'habitai---habit-tracker-12d13.firebasestorage.app',
    iosClientId: '1090097185211-e990h640aar5dlp3n1japnvaibtqq3ga.apps.googleusercontent.com',
    iosBundleId: 'com.jofu.habitai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHNl_Ys4big9EEfTouLpbXSa9h_5D4vgs',
    appId: '1:1090097185211:ios:5455a51679a59ef891849e',
    messagingSenderId: '1090097185211',
    projectId: 'habitai---habit-tracker-12d13',
    storageBucket: 'habitai---habit-tracker-12d13.firebasestorage.app',
    iosClientId: '1090097185211-lfbru3ainmn454amijr8ieqbcae7o6pq.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmH8z31ptDm3WVXU7npE2f8SOaejIbChc',
    appId: '1:1090097185211:web:c12279d73b42388e91849e',
    messagingSenderId: '1090097185211',
    projectId: 'habitai---habit-tracker-12d13',
    authDomain: 'habitai---habit-tracker-12d13.firebaseapp.com',
    storageBucket: 'habitai---habit-tracker-12d13.firebasestorage.app',
    measurementId: 'G-H6VC30V1YV',
  );
}