// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsDev {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqSeKzSbOp3wk0QkvGeEjn5reTaRL50GI',
    appId: '1:81812555129:android:daf51a4efcf52ecc375ba8',
    messagingSenderId: '81812555129',
    projectId: 'habitai-dev',
    storageBucket: 'habitai-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfMKGYT4PB7ozfuGta2CCWvn2bPWKqu7Q',
    appId: '1:81812555129:ios:2e12870e821bc760375ba8',
    messagingSenderId: '81812555129',
    projectId: 'habitai-dev',
    storageBucket: 'habitai-dev.firebasestorage.app',
    iosClientId: '81812555129-3u5d9hisclqrq0p626mc2p177f7ph66g.apps.googleusercontent.com',
    iosBundleId: 'com.jofu.habitai.dev',
  );

  // ✅ Add Web config here
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfMKGYT4PB7ozfuGta2CCWvn2bPWKqu7Q',
    authDomain: 'habitai-dev.firebaseapp.com',
    projectId: 'habitai-dev',
    storageBucket: 'habitai-dev.appspot.com',
    messagingSenderId: '81812555129',
    appId: '1:81812555129:web:abcdef123456',
    measurementId: 'G-XXXXXXX',
  );

}

