name: Flutter CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Use v3 for better version handling
      - uses: subosito/flutter-action@v3
        with:
          flutter-version: '3.35.5'  # exact Flutter version
          channel: 'stable'

      - run: flutter pub get

      - run: flutter format --set-exit-if-changed .

      - run: flutter analyze

      - run: flutter build apk --debug
